[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
